// <auto-generated />
using System;
using CompraProgramada.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompraProgramada.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompraProgramada.Api.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.ContaGrafica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("SaldoFinanceiro")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("NumeroConta")
                        .IsUnique();

                    b.ToTable("ContasGraficas");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.Custodia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaGraficaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId");

                    b.ToTable("Custodias");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.Distribuicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaGraficaId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrdemCompraId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorRateado")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId");

                    b.HasIndex("OrdemCompraId");

                    b.ToTable("Distribuicoes");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.HistoricoValorMensal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorAntigo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorNovo")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("HistoricoValoresMensais");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.HistoricoVenda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Lucro")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("HistoricoVendas");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.ItemCesta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CestaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PercentualPeso")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CestaId");

                    b.ToTable("ItensCesta");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.OrdemCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("QuantidadeTotal")
                        .HasColumnType("int");

                    b.Property<int>("Residuo")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoMercado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorTotalOperacao")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("OrdensCompra");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.TopFive", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("TopFive");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.ContaGrafica", b =>
                {
                    b.HasOne("CompraProgramada.Api.Models.Cliente", "Cliente")
                        .WithOne("ContaGrafica")
                        .HasForeignKey("CompraProgramada.Api.Models.ContaGrafica", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.Custodia", b =>
                {
                    b.HasOne("CompraProgramada.Api.Models.ContaGrafica", "ContaGrafica")
                        .WithMany("Custodias")
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.Distribuicao", b =>
                {
                    b.HasOne("CompraProgramada.Api.Models.ContaGrafica", "ContaGrafica")
                        .WithMany()
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompraProgramada.Api.Models.OrdemCompra", "OrdemCompra")
                        .WithMany("Distribuicoes")
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaGrafica");

                    b.Navigation("OrdemCompra");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.HistoricoValorMensal", b =>
                {
                    b.HasOne("CompraProgramada.Api.Models.Cliente", "Cliente")
                        .WithMany("HistoricosValor")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.HistoricoVenda", b =>
                {
                    b.HasOne("CompraProgramada.Api.Models.Cliente", "Cliente")
                        .WithMany("HistoricoVendas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.ItemCesta", b =>
                {
                    b.HasOne("CompraProgramada.Api.Models.TopFive", "Cesta")
                        .WithMany("Itens")
                        .HasForeignKey("CestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cesta");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.Cliente", b =>
                {
                    b.Navigation("ContaGrafica");

                    b.Navigation("HistoricoVendas");

                    b.Navigation("HistoricosValor");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.ContaGrafica", b =>
                {
                    b.Navigation("Custodias");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.OrdemCompra", b =>
                {
                    b.Navigation("Distribuicoes");
                });

            modelBuilder.Entity("CompraProgramada.Api.Models.TopFive", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
